### PR TITLE
Fix command error

### PR DESCRIPTION
**Pull request by sanderDijkxhoorn**
You broke the command cuz u completely removed the build folder, here is a quick fix ;)

### CODE REVIEW

**Comment by sanderDijkxhoorn** [comment]
I could also change it to delete if exists and then create it if you want.

**Comment by sourcelocation** [comment]
why did you close this issue? works perfectly for me

**Comment by sanderDijkxhoorn** [comment]
> why did you close this issue? works perfectly for me

It works fine but the project seems to be missing a roothelper so I was not able to actually test if it is working on a device.

**Comment by sanderDijkxhoorn** [comment]
I see that you have cleared the repo, I will check if it works later today.

**Comment by sanderDijkxhoorn** [comment]
The project builds and runs now. 👍

**Comment by sourcelocation** [comment]
👍

**Pull request closed without merging**
